### ISSUE TITLE
Strange Typeerror when changing goto_behaviour in a MockupRobot

### ISSUE THREAD

**Issue by show0k** [poppy-project/pypot#113]
If I change the goto_behaviour from 'minjerk' to 'dummy' in the setup() or the update() of a LoopPrimitive class, I got this TypeError:

``` bash
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/home/theo/miniconda/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/theo/miniconda/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/theo/Documents/code/pypot/pypot/utils/stoppablethread.py", line 119, in _wrapped_target
    self._target()
  File "/home/theo/Documents/code/pypot/pypot/utils/stoppablethread.py", line 179, in run
    make_update_loop(self, self._update)
  File "/home/theo/Documents/code/pypot/pypot/utils/stoppablethread.py", line 152, in make_update_loop
    update_func()
  File "/home/theo/Documents/code/pypot/pypot/primitive/manager.py", line 58, in update
    filtred_val = self._filter(val)
  File "/home/theo/miniconda/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 1719, in sum
    out=out, keepdims=keepdims)
  File "/home/theo/miniconda/lib/python2.7/site-packages/numpy/core/_methods.py", line 32, in _sum
    return umr_sum(a, axis, dtype, out, keepdims)
TypeError: cannot perform reduce with flexible type
```

Any idea @pierre-rouanet ?

**Comment by pierre-rouanet** [comment]
Unfortunately yes I understand why...

The idea is that everything that's set inside a primitive is automatically "combined" with the other value. For instance if you set the goal_position of the motor m0 to 20 in one primitive and to 40 in another one, 20 and 40 will be combined to give the real set goal_position.

By default, this combination is just a sum. Yet, sum just don't work on non numeric types. So if you affect anything which is not a numerical value inside a primitive you will get this error. 

I never really fix the problem (one easy solution would be to define another filter which sums if it's number and otherwise just returns the first element) because I never really find an elegant solution. It's part of the "re-write" entirely how primitives work to something better.
