### ISSUE TITLE
Frame is not serializable

### ISSUE THREAD

**Issue by TDiazT** [poppy-project/pypot#263]
I was trying out the API Rest and in particular, I tried accessing the frame from a camera sensor but I get a 500 error. I checked the logs in the robot's web interface and it says it is not serializable.
```python
Traceback (most recent call last):
  File "/home/poppy/miniconda/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/poppy/miniconda/bin/bottle.py", line 1733, in wrapper
    json_response = dumps(rv)
  File "/home/poppy/miniconda/lib/python2.7/site-packages/pypot/server/httpserver.py", line 70, in 
    jd = lambda s: json.dumps(s, cls=MyJSONEncoder)
  File "/home/poppy/miniconda/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/home/poppy/miniconda/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/poppy/miniconda/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/home/poppy/miniconda/lib/python2.7/site-packages/pypot/server/httpserver.py", line 31, in default
    return json.JSONEncoder.default(self, obj)
  File "/home/poppy/miniconda/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: 155 is not JSON serializable
500 GET /sensor/camera/register/frame (169.254.90.233) 25.03ms
```

Through the web interface, using the notebooks, it is possible to see the frame.. So I imagine the image is being transferred to my computer somehow. Is there a way of getting it through the rest api?

**Comment by TDiazT** [comment]
I just did a GET request with the following URL
<robot_name>.local:8080/sensor/camera/register/frame

I got an answer from Thibault (?) in the forum https://forum.poppy-project.org/t/get-picture-from-ergojr-camera-with-api-e-g-for-snap/3309/4?u=tdtron
